
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BEUEjercicio
{

using System;
    using System.Collections.Generic;
    
public partial class Calificacion
{

    public int idcalificacion { get; set; }

    public Nullable<decimal> valor { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

    public string unidad { get; set; }

    public Nullable<int> idmatricula { get; set; }



    public virtual Matricula Matricula { get; set; }

}

}
