
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BEUEjercicio
{

using System;
    using System.Collections.Generic;
    
public partial class Club
{

    public int id { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> minimoIntegrantes { get; set; }

    public Nullable<int> maximoIntegrantes { get; set; }

    public string instructor { get; set; }

    public string lugarEnsayos { get; set; }

}

}
